version: '3.7'

services:

  passwall-web:
    container_name: passwall-web
    image: passwall/passwall-web:latest
    restart: always
    build:
      context: .
    environment: 
      - PORT=3000
    ports:
      - 3000:3000